# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from contact import Contact

class TestTestaddcontact():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_add_contact(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.create_new_contact(Contact(firstname="imya", middlename="otchestvo", lastname="familiya",
                         nickname="prozvishe", title="zagolovok", company="kompaniya", address="adres",
                         home="domashnii", mobile="mobilnii", work="rabochii", fax="faks", email="miloraz",
                         email2="milodva", email3="milotri", homepage="domashnay_stranica", bday="1", bmonth="January",
                         byear="2021", aday="5", amonth="December", ayear="2022", address2="eshe_odin_adres",
                         phone2="houm"))
    self.return_to_home_page()
    self.logout()

  def test_add_empty_contact(self):
    self.open_home_page()
    self.login(username="admin", password="secret")
    self.create_new_contact(Contact(firstname="", middlename="", lastname="", nickname="", title="", company="",
                         address="", home="", mobile="", work="", fax="", email="", email2="", email3="", homepage="",
                         bday="", bmonth="", byear="", aday="", amonth="", ayear="", address2="", phone2=""))
    self.return_to_home_page()
    self.logout()

  def logout(self):
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def return_to_home_page(self):
    self.driver.find_element(By.LINK_TEXT, "home").click()

  def create_new_contact(self, contact):
    # open add new page
    self.driver.find_element(By.LINK_TEXT, "add new").click()
    # fill contact form
    self.driver.find_element(By.NAME, "firstname").send_keys(contact.firstname)
    self.driver.find_element(By.NAME, "middlename").send_keys(contact.middlename)
    self.driver.find_element(By.NAME, "lastname").send_keys(contact.lastname)
    self.driver.find_element(By.NAME, "nickname").send_keys(contact.nickname)
    self.driver.find_element(By.NAME, "title").send_keys(contact.title)
    self.driver.find_element(By.NAME, "company").send_keys(contact.company)
    self.driver.find_element(By.NAME, "address").send_keys(contact.address)
    self.driver.find_element(By.NAME, "home").send_keys(contact.home)
    self.driver.find_element(By.NAME, "mobile").send_keys(contact.mobile)
    self.driver.find_element(By.NAME, "work").send_keys(contact.work)
    self.driver.find_element(By.NAME, "fax").send_keys(contact.fax)
    self.driver.find_element(By.NAME, "email").send_keys(contact.email)
    self.driver.find_element(By.NAME, "email2").send_keys(contact.email2)
    self.driver.find_element(By.NAME, "email3").send_keys(contact.email3)
    self.driver.find_element(By.NAME, "homepage").send_keys(contact.homepage)
    dropdown = self.driver.find_element(By.NAME, "bday")
    dropdown.find_element(By.XPATH, "//option[. = '%s']" % contact.bday).click()
    dropdown = self.driver.find_element(By.NAME, "bmonth")
    dropdown.find_element(By.XPATH, "//option[. = '%s']" % contact.bmonth).click()
    self.driver.find_element(By.NAME, "byear").send_keys(contact.byear)
    dropdown = self.driver.find_element(By.NAME, "aday")
    dropdown.find_element(By.XPATH, "//option[. = '%s']" % contact.aday).click()
    dropdown = self.driver.find_element(By.NAME, "amonth")
    dropdown.find_element(By.XPATH, "//option[. = '%s']" % contact.amonth).click()
    self.driver.find_element(By.NAME, "ayear").send_keys("%s" % contact.ayear)
    self.driver.find_element(By.NAME, "address2").send_keys(contact.address2)
    self.driver.find_element(By.NAME, "phone2").send_keys(contact.phone2)
    # submit contact creation
    self.driver.find_element(By.XPATH, "(//input[@name=\'submit\'])[2]").click()

  def login(self, username, password):
    self.driver.find_element(By.NAME, "user").send_keys(username)
    self.driver.find_element(By.NAME, "pass").send_keys(password)
    self.driver.find_element(By.XPATH, "//input[@value=\'Login\']").click()

  def open_home_page(self):
    self.driver.get("http://localhost/addressbook/")
  
